# Generated by Django 5.0.4 on 2024-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_payment_payé_planning_apc_alter_rendezvous_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='date_rendez_vous',
            field=models.DateTimeField(),
        ),
    ]
