# Generated by Django 5.0.4 on 2024-04-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_gouvernorat_grade_groupe_hopital_nationalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='tarif',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
