# Generated by Django 5.0.4 on 2024-05-06 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_groupe_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_naiss',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gouvernorat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gouv', to='account.gouvernorat'),
        ),
    ]
