# Generated by Django 5.0.4 on 2024-05-06 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_date_naiss_alter_user_gouvernorat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gouvernorat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gouv', to='account.gouvernorat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat', to='account.nationalite'),
        ),
    ]
