# Generated by Django 5.0.4 on 2024-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='sepcialite',
            new_name='specialite',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=1000000, primary_key=True, serialize=False, unique=True),
        ),
    ]
