# Generated by Django 5.0.4 on 2024-05-17 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_sepcialite_medecin_specialite_alter_user_id'),
        ('chat', '0002_alter_message_options_alter_message_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='medecin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='roommed', to='account.medecin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='account.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.message')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
        ),
    ]
